#!/usr/bin/expect

set timeout 0
#set user test
#set pass qwerty

spawn telnet localhost 

expect "login: "
send "test\r"

expect "Password: "
send "qwerty\r"


expect "bash-4.1$"
send "scp /usr/Trans/translategui test@localhost:/var/guinew\r"

expect "test@localhost's passowrd:"
send "qwerty\r"

expect "bash-4.1$"
send "exit\r"

spawn /var/./guinew 
interact

spawn rm -f /var/guinew 
interact
#spawn /var/./guinew\r
